version: '3'
services:
  pubsub-emulator:
    image: aongko/pubsub-emulator
    build: .
    ports:
      - "8085:8085"
    volumes:
      - ./data:/data
    command: ["--host-port=0.0.0.0:8538", "--data-dir=/data"]
